name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # 매일 03:00 JST
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: generate-github-profile-3d-contrib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 3D GitHub Profile
        uses: yoshi389111/github-profile-3d-contrib@v0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "Jade-Good"
          git config user.email "kangsm423@gmail.com"
          git add -A
          git commit -m "generated" || echo "no changes to commit"
          git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}
